# Generated by Django 4.2.3 on 2023-08-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPRegistro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='default_hashed_password', max_length=128),
        ),
    ]
